version: 0.0
os: windows
files:
 - source: .
   destination: C:\xampp\htdocs\simple-vue-todo
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root