name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
jobs:
  continuous-integration:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

        # Install Python Dependencies
      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

        # Build App and Run Application Test
      - name: Build Application and Run unit Test
        run: npm run build

  continuous-deployment:
    runs-on: windows-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Create CodeDeploy Deployment
        id: deploy
        run: aws deploy create-deployment --application-name teledoctor --deployment-group-name PreDeployment --deployment-config-name CodeDeployDefault.OneAtATime --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
